### ISSUE TITLE
jQuery not listed as dependecy

### ISSUE THREAD

**Issue by jdescelliers** [clarketm/image-map#14]
When I install only `image-map` module with yarn with:
```console
yarn add image-map
```
then when importing imageMap it crashes because jQuery is not defined.

There are problems here:
- jQuery should be optional
- if jQuery is absolutely required, then it should be listed as an dependency.

Can you make jQuery optional?

I couldn't find any options to perform a yarn add image-map --with-peer-dependencies` since it doesn't exist.

**Comment by clarketm** [comment]
> then when importing imageMap it crashes because jQuery is not defined.

It should not crash, butit will give a warning about a missing peer dependency.

![image](https://user-images.githubusercontent.com/9957358/79386919-b6742480-7f1f-11ea-9b54-4d75c111ae60.png)

> jQuery should be optional
> ...
> Can you make jQuery optional?

jQuery is indeed _optional_, since the plugin works with plain JS ([ref](https://github.com/clarketm/image-map#javascript-vanilla-js)). But, of course, it can also be used with jQuery ([ref](https://github.com/clarketm/image-map#jquery)).

**Comment by clarketm** [comment]
@jdescelliers - it looks like this line in the bundled dist is the culprit. I will push a fix once I get the bundler properly configured.

https://github.com/clarketm/image-map/blob/0217b18fb1b07c0c15ef6c6db0571831fa5e7ccb/dist/image-map.es.js#L8

**Comment by clarketm** [comment]
I published `image-map` [v2.0.0](https://github.com/clarketm/image-map/releases/tag/v2.0.0) which no longer depends on JQuery. The jQuery version is now a [separate script](https://github.com/clarketm/image-map#jquery).
