### ISSUE TITLE
Performance with lots of areas

### ISSUE THREAD

**Issue by Ryvix** [clarketm/image-map#5]
Hi there,

I thought I should post it here in case it's useful to anyone.

I noticed when making a whole lot areas this script will slow right down. I fixed it by changing the lines around [line 52](https://github.com/clarketm/image-map/blob/master/image-map.js#L52) to:

```javascript
					document.querySelectorAll('map[name="' + map + '"] area').forEach(function () {
						var coordsS = this.dataset[c] = this.dataset[c] || this.getAttribute(c),
							coordsA = coordsS.split(','),
							coordsPercent = Array.apply(null, Array(coordsA.length));

						coordsPercent.forEach(function (val, i) {
							coordsPercent[i] = i % 2 === 0 ? Number(((coordsA[i] / w) * 100) * wPercent) : Number(((coordsA[i] / h) * 100) * hPercent);
						});
						this.setAttribute(c, coordsPercent.toString());
					});
```
I'm not completely sure what effect this has such as if it's compatible with older browsers or whatever but it seems to work and doesn't slow my browser down like before.

**Comment by clarketm** [comment]
@Ryvix – It makes senses that calling `forEach` directly on the NodeList would be faster than using `.call` but I have yet to run any performance testing on this so I was not aware the difference was so drastic. I can check on the browser compatibility in more detail; Do you mind PRing the change? I appreciate your contribution!

**Comment by clarketm** [comment]
@Ryvix - can you try adding this polyfill and see if the performance issues you are experiencing are remedied?

```javascript
if (window.NodeList && !NodeList.prototype.forEach) {
    NodeList.prototype.forEach = function (callback, thisArg) {
        thisArg = thisArg || window;
        for (var i = 0; i < this.length; i++) {
            callback.call(thisArg, this[i], i, this);
        }
    };
}
```

**Comment by clarketm** [comment]
@Ryvix – Based on your feedback, I made several performance improvements and published them in the latest release [v1.0.9](https://github.com/clarketm/image-map/releases/tag/v1.0.9). Please pull that new version and let me know if this fixes the problem. I appreciate your contribution!

**Comment by Ryvix** [comment]
Oh awesome, thank you! Yes, there were 10s of thousands of areas in the image map I was working with and it was slowing the browser down until I changed that. I will test it out today and see how it goes. I'm sure it's probably all better now. Thanks!

**Comment by Ryvix** [comment]
OK I tested it and it seems fine in Chrome but in Firefox it still slows down until I remove the `val` arg like shown in the code above and use `this` instead within the loop.

**Comment by clarketm** [comment]
@Ryvix - I understand what you are saying, but the issue is that ‘this’ ans ‘val’ are not the same value in this context. By changing ‘val’ -> ‘this’ you are essentially disabling the *dynamic* resizing of the image map on viewport change. This explains why it is more performant but unfortunately will break the benefit of the plugin.

**Comment by clarketm** [comment]
@Ryvix – I decided to rewrite the library using modern es6 syntax, eliminating a bunch of dead code in the process. I no longer have the *browser compatibility* constraint now since the source code is transpiled through babel in the build process. My expectation is that this effort is a step in the right direction for achieving a performance optimization. One such addition is the ability to pass a [debounce](https://github.com/clarketm/image-map#javascript-vanilla-js) wait interval as an argument to the `ImageMap` constructor.

In the near future, when I free up more time, I will make additional strides to boost performance. In the meantime, if you have any additional suggestions feel free to comment or create a PR. Thanks again for you contribution!

**Comment by Ryvix** [comment]
Amazing, thank you!
